### ISSUE TITLE
Why is shared_ptr not used to manage memory in the project?

### ISSUE THREAD

**Issue by mystery-nobody** [sogou/workflow#428]

**Comment by Barenboim** [comment]
Because I don't like shared_ptr. I think it's ugly. So shared_ptr has never been an option from the very beginning. We have also developed the mechanism of memory management for user interfaces. **Tasks** are the only objects that interact with users, and each task has a very precise lifecycle, from the creation to the callback. The definition is so simple no user has complained about memory leak or memory management problem up to this moment. 
I hope this explanation helps.
