### ISSUE TITLE
Streaming for large file?

### ISSUE THREAD

**Issue by SHiftLin** [sogou/workflow#715]
In the tutorial of file server and proxy server,  the framework needs to wait until the whole file gets read in order to respond to the client. Can the framework stream the large file to the client?

**Comment by Barenboim** [comment]
Workflow is not very suitable for streaming server. You may use WFServer's 'push()' method to build a simple**feed** server. But to implement a streaming proxy, you will still need to override 'append()' of the message in order to transfer data while receiving. Here is some information of server's push(): https://github.com/sogou/workflow/issues/628#issuecomment-962638634

**Comment by SHiftLin** [comment]
Thanks for your reply! I will try push()
