### ISSUE TITLE
Fedora因没有libpthread.so导致编译失败

### ISSUE THREAD

**Issue by SkyTeamWater** [sogou/workflow#728]
如题，希望改一下CMakelist

**Comment by chanchann** [comment]
这种一般不是cmake的问题吧，这种情况一般需要你自己ln -s一下

**Comment by holmes1412** [comment]
看起来是你的libpthread.so位置有问题呢，或者默认安装路径被改过之类的。
你可以 `find / -name libpthread.so `看看你的环境下libpthread.so在哪，然后把那个路径配到`/etc/ld.so.conf`这个文件里的一行就可以了。具体操作步骤也可以网上查查linux系统找不到.so文件之类的解决办法。

**Comment by SkyTeamWater** [comment]
![image](https://user-images.githubusercontent.com/51621873/149955442-566f947c-050f-480d-99ab-47614608eee2.png)
其他平台都能编译过，唯独Fedora

**Comment by SkyTeamWater** [comment]
用的github的ci应该不存在位置有问题

**Comment by holmes1412** [comment]
你好，请问是否已经解决了呢？这个感觉比较奇怪，不太应该发生～

**Comment by cnmade** [comment]
you need check if the libpthread.so is exists, if not exists, you can see error logs:

cannot find -lpthread.so
for amd64 , if not exists, you may want to ln -s it.

ln -s /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so
for ARM64 , you can try

ln -s /lib/aarch64-linux-gnu/libpthread.so.0 /lib/aarch64-linux-gnu/libpthread.so

Tested for ubuntu , may fedora got the same problem. 
because the default libpthread.so.0  no link to libpthread.so
