### ISSUE TITLE
Issue in transferring data between tasks

### ISSUE THREAD

**Issue by SundaramRathinam** [sogou/workflow#896]
Hi ,

Facing issue in transferring data from one task to another task, Attached sample code that i am using
Whether i am doing the wrong way
[Code.txt](https://github.com/sogou/workflow/files/8668314/Code.txt)
![Output](https://user-images.githubusercontent.com/105350782/167810444-8c20db0f-b578-4728-8a0f-629075b39fab.JPG)
?

**Comment by Barenboim** [comment]
Hi.
This is a question frequently asked. We'v not provided a common way for passing data between graph task's nodes. Indeed, any method, the cost of passing data between each pair of preceder and successor will be very significant. Some other graph engine like [taskflow](https://github.com/taskflow/taskflow) is facing the same problem. You may check out this issue: https://github.com/taskflow/taskflow/issues/41
If you are using parallel-series structure instead of DAG, you may simply use series' context to pass data.

**Comment by SundaramRathinam** [comment]
Thanks for your inputs
