### ISSUE TITLE
Segment fault after calling SeriesWork::cancel() in the WFServerTask

### ISSUE THREAD

**Issue by yuxilao** [sogou/workflow#933]
WFServerTask::done() has a deferred deletion which is called by the destructor of SeriesWork.
And when I call SeriesWork::cancel(),it delete the task immediately which cause duplicated deletion of WFServerTask.
Is there any solution?  

By the way,I want to combine two SeriesWork,the first one for WFServerTask and the second one for querying the database.
In the second one,i want to interrupt  it when the database return unexpected data.
Is there any better suggestion for me？

Thank you！

**Comment by Barenboim** [comment]
Fixed in this PR: https://github.com/sogou/workflow/pull/934

**Comment by Barenboim** [comment]
@yuxilao Could you make a check on this change? Thanks.
And in your scenario I adivise using WFModuleTask and you can cancel the sub-series in your module. Because canceling the server task series will subsequently close the connection, and I think the server is supposed to reply with some error messages. By using module, you can check also check the sub-series' cancelation state in module task' callback.
